# SPDX-FileCopyrightText: Copyright © DUNE Project contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-DUNE-exception

Module: dune-localfunctions
Version: 2.10-git
Author: The Dune Core developers
Maintainer: dune-devel@lists.dune-project.org
Description: Provides interface and implementation for shape functions defined on the DUNE reference elements
URL: https://gitlab.dune-project.org/core/dune-localfunctions
Python-Requires:
Depends: dune-geometry (>= 2.9)
Whitespace-Hook: Yes
