#dune module information file#
##############################

#Name of the module
Module: dune-localfunctions
Version: 2.0beta1
Maintainer: dune@dune-project.org
#depending on
# the dune-grid dependency can be downgraded to a Suggests: once the
# referenceelements are untangled from the p0 functions.
Depends: dune-common (>= 2.0) dune-grid (>= 2.0)
# Needed for the debugging vtk output program
Suggests: dune-grid (>= 2.0)
